# Build the manager binary
# Nyamber depends on cybozu-go/placemat. Since cybozu-go/placemat does not support Ubuntu 24.04 yet, use a jammy-based image.
FROM ghcr.io/cybozu/golang:1.27.1.1_jammy@sha256:cf6a363d2a421e18a4e0038b69f0b44061903a98ab4c58ea46a68c271e81b327 AS builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN --mount=type=cache,target=/go/pkg/mod go mod download

# Copy the go source
COPY cmd/ cmd/
COPY pkg/ pkg/

# Build
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o entrypoint cmd/entrypoint/main.go

# Nyamber depends on cybozu-go/placemat. Since cybozu-go/placemat does not support Ubuntu 24.04 yet, use a jammy-based image.
FROM ghcr.io/cybozu/ubuntu:22.04.20260916@sha256:fb80e128ca6b7fd2a3e165e18df5defb2eb677f207d45b7d6dc35ed1597a4cd4
LABEL org.opencontainers.image.source=https://github.com/cybozu-go/nyamber

# renovate: datasource=golang-version depName=go
ENV GO_VERSION=1.27.1
ENV GO_SHA=63d339f0da5ab53635a56f2490a7984dfe12dfcff22ad749f63edaf590168445
# renovate: datasource=github-releases depName=cybozu-go/placemat
ENV PLACEMAT_VERSION=2.7.1
ENV PLACEMAT_SHA=ff1686ae04496c5dacde74cb4acb79a4cd5ed8c53a49b14eaf281f2951896710
ENV AQUA_INSTALLER_VERSION=v4.0.5
ENV AQUA_INSTALLER_SHA=451028d56959cc738564885b1dbebc2691ea038ffde04e2472e4d486a3591146
ENV AQUA_VERSION=v2.62.3

ENV HOME=/home/nyamber
ENV GOPATH=${HOME}/go
ENV GOBIN=${GOPATH}/bin
ENV PATH=${HOME}/.local/share/aquaproj-aqua/bin:/usr/local/aquaproj-aqua/bin:${GOBIN}:/usr/local/go/bin:${PATH}
ENV NECO_DIR=${GOPATH}/src/github.com/cybozu-go/neco
ENV NECO_APPS_DIR=${GOPATH}/src/github.com/cybozu-private/neco-apps

# Avoid bird post-installation script error
# See https://bird.network.cz/pipermail/bird-users/2019-December/014075.html
COPY include-bird /etc/dpkg/dpkg.cfg.d/

RUN curl -sSLf https://cli.github.com/packages/githubcli-archive-keyring.gpg -o /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list \
    && apt-get update \
    && apt-get -y install --no-install-recommends \
            bash-completion \
            bird2 \
            build-essential \
            cloud-utils \
            dbus \
            dnsmasq \
            fakeroot \
            freeipmi-tools \
            gh \
            git \
            iproute2 \
            iptables \
            jq \
            kmod \
            less \
            libgpgme11 \
            lldpd \
            lsb-release \
            qemu \
            qemu-kvm \
            openssh-client \
            picocom \
            socat \
            squid \
            sudo \
            swtpm \
            systemd-container \
            time \
            unzip \
            wget \
            xauth \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSLf -o go.tar.gz "https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz" \
    && echo "${GO_SHA}  go.tar.gz" | sha256sum -c - \
    && tar -C /usr/local -xzf go.tar.gz \
    && rm go.tar.gz \
    && curl -sSLf -o placemat2.deb "https://github.com/cybozu-go/placemat/releases/download/v${PLACEMAT_VERSION}/placemat2_${PLACEMAT_VERSION}_amd64.deb" \
    && echo "${PLACEMAT_SHA}  placemat2.deb" | sha256sum -c - \
    && dpkg -i placemat2.deb \
    && rm placemat2.deb \
    && curl -sSfL -O https://raw.githubusercontent.com/aquaproj/aqua-installer/${AQUA_INSTALLER_VERSION}/aqua-installer \
    && echo "${AQUA_INSTALLER_SHA}  aqua-installer" | sha256sum -c - \
    && chmod +x aqua-installer \
    # /home/nyamber is where a separate volume will be mounted,
    # so install aqua itself under /usr/local/aquaproj-aqua instead.
    && AQUA_ROOT_DIR=/usr/local/aquaproj-aqua ./aqua-installer -v ${AQUA_VERSION} \
    && rm ./aqua-installer \
    && echo "nyamber ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers \
    && adduser --disabled-password --gecos "" --uid 10000 nyamber \
    && chown -R nyamber:nyamber ${HOME}

WORKDIR /
COPY --from=builder /workspace/entrypoint .
USER nyamber

ENTRYPOINT ["/entrypoint"]
