apiVersion: v1
kind: Pod
spec:
  containers:
  - image: localhost:5151/nyamber-runner:dev
    name: ubuntu
    command:
      - "/entrypoint" 
    volumeMounts:
    - name: scripts
      mountPath: /scripts
  volumes:
  - name: scripts
    configMap:
      name: scripts
      defaultMode: 0555
