apiVersion: v1
kind: Pod
spec:
  containers:
  - image: localhost:5151/entrypoint:dev
    imagePullPolicy: Always
    name: ubuntu
    command:
      - "/entrypoint" 
      - "test:touch /tmp/hello"
      - "test_long_run:sleep 60"
