---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nyamber-cybozu-io-v1beta1-autovirtualdc
  failurePolicy: Fail
  name: vautovirtualdc.kb.io
  rules:
  - apiGroups:
    - nyamber.cybozu.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autovirtualdcs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nyamber-cybozu-io-v1beta1-virtualdc
  failurePolicy: Fail
  name: vvirtualdc.kb.io
  rules:
  - apiGroups:
    - nyamber.cybozu.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualdcs
  sideEffects: None
