# permissions for end users to edit autovirtualdcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autovirtualdc-editor-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - nyamber.cybozu.io
  resources:
  - autovirtualdcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nyamber.cybozu.io
  resources:
  - autovirtualdcs/status
  verbs:
  - get
