---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nyamber.cybozu.io
  resources:
  - autovirtualdcs
  - virtualdcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nyamber.cybozu.io
  resources:
  - autovirtualdcs/status
  - virtualdcs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nyamber.cybozu.io
  resources:
  - virtualdcs/finalizers
  verbs:
  - update
