---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nyamber.nyamber.cybozu.io
  resources:
  - virtualdcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nyamber.nyamber.cybozu.io
  resources:
  - virtualdcs/finalizers
  verbs:
  - update
- apiGroups:
  - nyamber.nyamber.cybozu.io
  resources:
  - virtualdcs/status
  verbs:
  - get
  - patch
  - update
