# permissions for end users to view virtualdcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualdc-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - nyamber.cybozu.io
  resources:
  - virtualdcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nyamber.cybozu.io
  resources:
  - virtualdcs/status
  verbs:
  - get
