apiVersion: nyamber.cybozu.io/v1beta1
kind: AutoVirtualDC
metadata:
  name: auto-virtual-dc
spec:
  template:
    spec:
        necoBranch: release
        necoAppsBranch: release
        command:
        - env
  timeoutDuration: "20m"
