name: Setup aqua
description: Install aqua and tools
inputs:
  aqua_version:
    description: aqua version to install
    required: true
  github_token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
      with:
        aqua_version: ${{ inputs.aqua_version }}
        github_token: ${{ inputs.github_token }}
