name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
env:
  cache-version: 1
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: make docker-build
  test:
    name: Small tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - run: make setup
    - run: make fmt
    - run: make vet
    - run: make check-generate
    - run: make test
  e2e:
    name: End-to-End Tests
    strategy:
      matrix:
        kind-image-ref:
          - "v1.31.9@sha256:b94a3a6c06198d17f59cca8c6f486236fa05e2fb359cbd75dabbfc348a10b211"
          - "v1.32.5@sha256:e3b2327e3a5ab8c76f5ece68936e4cafaa82edf58486b769727ab0b3b97a5b0d"
          - "v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0  # v4.0.0
      with:
        aqua_version: v2.53.3
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract kubernetes version from kind-image-ref
      id: k8s-version
      run: |
        KIND_IMAGE_REF="${{ matrix.kind-image-ref }}"
        VERSION=$(echo "$KIND_IMAGE_REF" | awk -F '[@v]' '{print $2}')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - run: make setup KIND_IMAGE_REF=${{ matrix.kind-image-ref }}
      working-directory: e2e
    - run: make start KIND_IMAGE_REF=${{ matrix.kind-image-ref }}
      working-directory: e2e
    - run: make test
      working-directory: e2e
    - run: make logs
      working-directory: e2e
      if: always()
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs-${{ steps.k8s-version.outputs.version }}.tar.gz
        path: e2e/logs.tar.gz
