name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
env:
  cache-version: 1
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: make docker-build
  test:
    name: Small tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - run: make setup
    - run: make fmt
    - run: make vet
    - run: make check-generate
    - run: make test
  e2e:
    name: End-to-End Tests
    strategy:
      matrix:
        kind-image-ref:
          - "v1.32.8@sha256:abd489f042d2b644e2d033f5c2d900bc707798d075e8186cb65e3f1367a9d5a1"
          - "v1.33.4@sha256:25a6018e48dfcaee478f4a59af81157a437f15e6e140bf103f85a2e7cd0cbbf2"
          - "v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0  # v4.0.0
      with:
        aqua_version: v2.53.3
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract kubernetes version from kind-image-ref
      id: k8s-version
      run: |
        KIND_IMAGE_REF="${{ matrix.kind-image-ref }}"
        VERSION=$(echo "$KIND_IMAGE_REF" | awk -F '[@v]' '{print $2}')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - run: make setup KIND_IMAGE_REF=${{ matrix.kind-image-ref }}
      working-directory: e2e
    - run: make start KIND_IMAGE_REF=${{ matrix.kind-image-ref }}
      working-directory: e2e
    - run: make test
      working-directory: e2e
    - run: make logs
      working-directory: e2e
      if: always()
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs-${{ steps.k8s-version.outputs.version }}.tar.gz
        path: e2e/logs.tar.gz
