name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
env:
  go-version: 1.18
  cache-version: 1
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: make docker-build
  test:
    name: Small tests
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go-version }}
    - run: make test
