name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
env:
  cache-version: 1
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: make docker-build
  test:
    name: Small tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - run: make setup
    - run: make fmt
    - run: make vet
    - run: make check-generate
    - run: make test
  e2e:
    name: End-to-End Tests
    strategy:
      matrix:
        k8s-version: ["1.28.13", "1.29.8", "1.30.4"]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
      with:
        aqua_version: v2.27.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: make setup E2ETEST_K8S_VERSION=${{ matrix.k8s-version }}
      working-directory: e2e
    - run: make start E2ETEST_K8S_VERSION=${{ matrix.k8s-version }}
      working-directory: e2e
    - run: make test
      working-directory: e2e
    - run: make logs
      working-directory: e2e
      if: always()
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs-${{ matrix.k8s-version }}.tar.gz
        path: e2e/logs.tar.gz
