name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
env:
  cache-version: 1
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - run: make docker-build
  test:
    name: Small tests
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: go.mod
    - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c  # v4.0.4
      with:
        aqua_version: v2.55.3
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - run: make fmt
    - run: make vet
    - run: make check-generate
    - run: make test
  e2e:
    name: End-to-End Tests
    strategy:
      matrix:
        kind-image-ref:
          - "v1.32.11@sha256:5fc52d52a7b9574015299724bd68f183702956aa4a2116ae75a63cb574b35af8" # renovate:
          - "v1.33.7@sha256:d26ef333bdb2cbe9862a0f7c3803ecc7b4303d8cea8e814b481b09949d353040" # renovate:
          - "v1.34.3@sha256:08497ee19eace7b4b5348db5c6a1591d7752b164530a36f855cb0f2bdcbadd48" # renovate:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: go.mod
    - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c  # v4.0.4
      with:
        aqua_version: v2.55.3
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract kubernetes version from kind-image-ref
      id: k8s-version
      run: |
        KIND_IMAGE_REF="${{ matrix.kind-image-ref }}"
        VERSION=$(echo "$KIND_IMAGE_REF" | awk -F '[@v]' '{print $2}')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - run: make setup KIND_IMAGE_REF=${{ matrix.kind-image-ref }}
      working-directory: e2e
    - run: make start KIND_IMAGE_REF=${{ matrix.kind-image-ref }}
      working-directory: e2e
    - run: make test
      working-directory: e2e
    - run: make logs
      working-directory: e2e
      if: always()
    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      if: always()
      with:
        name: logs-${{ steps.k8s-version.outputs.version }}.tar.gz
        path: e2e/logs.tar.gz
