name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
env:
  cache-version: 1
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: make docker-build
  test:
    name: Small tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - run: make setup
    - run: make fmt
    - run: make vet
    - run: make check-generate
    - run: make test
  e2e:
    name: End-to-End Tests
    strategy:
      matrix:
        k8s-version: ["1.23.13", "1.24.7", "1.25.3"]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 #v2.0.2
      with:
        aqua_version: v1.32.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: make setup E2ETEST_K8S_VERSION=${{ matrix.k8s-version }}
      working-directory: e2e
    - run: make start E2ETEST_K8S_VERSION=${{ matrix.k8s-version }}
      working-directory: e2e
    - run: make test
      working-directory: e2e
    - run: make logs
      working-directory: e2e
      if: always()
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: logs-${{ matrix.k8s-version }}.tar.gz
        path: e2e/logs.tar.gz
